config/routes.rb
RailsStore::Application.routes.draw do
  resources :reviews, :only => [:new, :show, :edit, :create]

  resources :products

  root :to => 'products#index'

end

app/models/product.rb
require 'open-uri'
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :google, :description, :in_cart, :image_url
  has_many :reviews
  validates :name, :uniqueness => true
  validates :name, :price, :presence => true
  def google(name)
    key = "AIzaSyDk3hh_cS7FVlcV1AgzQdIk89RZzGiQwzI"
    file = open("https://www.googleapis.com/shopping/search/v1/public/products?key=#{key}&country=US&q=#{URI.escape(name)}&alt=json")
    JSON.load(file.read)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :body, :product_id, :rating
  belongs_to :product
  validates :body, :length => { :in => 50..1000 }
  validates :rating, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  before_filter :products_array

  def products_array
    @products = Product.all.to_a
  end

  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @id = params[:id]
    p = Product.new
    @product = Product.find(@id)
    @review = Review.new
    @product_reviews = Review.where(:product_id => @id)
    @list = p.google(@product.name)
    @picture = @list['items'][0]['product']['images'][0]['link']
    @link = @list['items'][0]['product']['link']
    @description = @list['items'][0]['product']['description']
    # @total = @products.map{|sum, n| sum + n }
    @average = @product_reviews.average('rating')


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    @list = @product.google(@product.name)
    @picture = @list['items'][0]['product']['images'][0]['link']
    @link = @list['items'][0]['product']['link']
    @description = @list['items'][0]['product']['description']
    @product.image_url = @picture

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new
    @all_reviews = Review.all

  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def total
    total = Product.select("price").where(:in_cart => true)
    total.sum(:price)
    # total.to_a.inject{|sum, n| sum + n}
  end
  def in_cart_items
     Product.where(:in_cart => true)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Store</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Signika+Negative:600|Yesteryear' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <ul>
    <li><%= link_to "Products", products_path %></li>
    <li><%= link_to "New Product", new_product_path %></li>
  </ul>
</nav>

<div class="onepcssgrid-1000">
  <%= yield %>
</div>


</body>
</html>

app/views/products/_cart_form.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <% if @product.in_cart == true %>
    <%= f.hidden_field :in_cart, :value => false %>
  <% else %>
    <%= f.hidden_field :in_cart, :value => true %>
  <% end %>
  </div>
  <div class="actions">
    <% if @product.in_cart == true %>
      <%= f.submit "Remove from Cart", :class => "button" %>
  <% else %>
    <%= f.submit "Add to Cart", :class => 'button' %>
  <% end %>
  </div>
<% end %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.hidden_field :description, :value => @description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_list.erb
<% if @product_reviews.empty? %>
  <h2>Be the first to Review</h2>
<% else %>
<h2>Reviews for <%= @product.name %></h2>
<% end %>
  <% @product_reviews.each do |review| %>
     <div class="review-wrapper">
        <p>
          <b>Body:</b>
          <%= review.body %>
        </p>

        <p>
          <b>Rating:</b>
          <%= review.rating %>
        </p>
      </div>
      <br />
<% end %>
<%= render 'products/reviews' %>
       

app/views/products/_reviews.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.hidden_field :product_id, :value => params[:id] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_shopping_cart.erb
<div id="shopping-cart">
  <% in_cart_items.each do |product| %>
  <p>
    <b><%= product.name %>:</b>
      <%= number_to_currency(product.price) %>
  </p>
  <% end %>
  <p>
    <b>Total:</b>
  <%= number_to_currency(total) %>
  </p>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class='onerow'>
    <br />
    <br />
  <div class="col10">
  <ul>
<% @products.each do |product| %>
    <div class='col3'>
      <h3><%= product.name %></h3>
      <h3><%= '$' + product.price.to_s %></h3>
      <%= link_to image_tag(product.image_url), product %>
      <%= link_to 'Edit', edit_product_path(product) %>
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
<% end %>
  </ul>
  </div>
  <div class="col2 last">
    <%= render 'products/shopping_cart'  %>
  </div>
</div>

app/views/products/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
    <h1><%= @product.name.upcase %></h1> 
    <br />
<p id="notice"><%= notice %></p>
<div class="onerow">
  <div class="col3">
      <b>Average Rating:</b>
    <%= @average %>
    </p>
    <p>
      <b>Price:</b>
      <%= number_to_currency(@product.price) %>
    </p>
    <p>
      <b>Description:</b>
      <%= @description %>
    </p>

    <%= link_to 'Edit', edit_product_path(@product) %> |
    <%= link_to 'Back', products_path %>
  </div>
  <div class="col5">
    <%= image_tag @product.image_url %>
  </div>
  <div class="col4 last">
    <%= render 'products/shopping_cart'  %>
    <%= render 'products/cart_form' %>
    <%= render 'products/list'  %>
  </div>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <% products_array = Product.all.map{|products| [products.id, products.name] } %>
    <%= f.label :products %>
    <%= options_for_select(products_array) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Rating</th>
    <th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.body %></td>
    <td><%= review.rating %></td>
    <td><%= review.product_id %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @review.body %>
</p>

<p>
  <b>Rating:</b>
  <%= @review.rating %>
</p>

<p>
  <b>Product:</b>
  <%= @review.product_id %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', products_path %>